
// Home
GET http://localhost:8000


### Get all pemasok
GET http://localhost:8000/pemasoks

### Get detail pemasok
GET http://localhost:8000/pemasoks/1

### Create pemasok data
POST http://localhost:8000/pemasoks
Content-Type: application/json

{
    "pemasok_id": "1",
    "nama": "yanto"
}

### Update pemasok data
PUT http://localhost:8000/pemasoks/1
Content-Type: application/json

{
    "name": "yanti"
}

### Delete pemasok data
DELETE  http://localhost:8000/suppliers/1


# ### Get all components
# GET http://localhost:8000/components


# ### Get detail component
# GET http://localhost:8000/components/1


# ### Create component data
# POST http://localhost:8000/components
# Content-Type: application/json

# {
#     "name": "lorem ipsum",
#     "description": "lorem ipsum"
# }


# ### Update component data
# PUT http://localhost:8000/components/1
# Content-Type: application/json

# {
#     "name": "Ganti judul"
#     // "description": "Ganti description"
# }


# ### Delete component data
# DELETE  http://localhost:8000/components/1

# #####################################################################################################################################

# ### Get all products
# GET http://localhost:8000/products


# ### Get detail product
# GET http://localhost:8000/products/1


# ### Create product data
# POST http://localhost:8000/products
# Content-Type: application/json

# {
#     "name": "ini produk",
#     "quantity": 10
# }


# ### Update product data
# PUT http://localhost:8000/products/1
# Content-Type: application/json

# {
#     "name": "Ganti judul"
#     // "quantity": 5
# }


# ### Delete product data
# DELETE  http://localhost:8000/products/1


# #####################################################################################################################################

# ### Get all product_components
# GET http://localhost:8000/product_components


# ### Get detail product_component
# GET http://localhost:8000/product_components/1


# ### Create product_component data
# POST http://localhost:8000/product_components
# Content-Type: application/json

# {
#     "product_id": 1,
#     "component_id": 1
# }


# ### Update product_component data
# PUT http://localhost:8000/product_components/1
# Content-Type: application/json

# {
#     "name": "Ganti judul"
#     // "description": "Ganti description"
# }


# ### Delete product_component data
# DELETE  http://localhost:8000/product_components/1




